// Bit-parity against NumPy 2.0.2 — layered vectors generated by
// tools/reference (tests/golden/np-parity-vectors.json). Every comparison is
// exact (===): the §7.3 contract is bit-identical cross-language streams.

import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";
import { Pcg64, seedFromObject } from "./rng";
import { sampleBeta, sampleGamma } from "./gamma-beta";

const VEC = JSON.parse(
  readFileSync(new URL("../../tests/golden/np-parity-vectors.json", import.meta.url), "utf8"),
);

const seed121 = seedFromObject("§12.1 AP Royal Oak 5516", "2026-07-13T00:00:00Z").seed;

describe("NumPy bit-parity (layered)", () => {
  it("seed derivation matches the reference", () => {
    expect(seed121).toBe(BigInt(VEC.seed_12_1));
  });

  it("raw 64-bit PCG64 stream matches", () => {
    const rng = new Pcg64(seed121);
    for (let i = 0; i < VEC.layers.raw64.length; i++) {
      expect(rng.next64()).toBe(BigInt(VEC.layers.raw64[i]));
    }
  });

  it("uniform doubles match", () => {
    const rng = new Pcg64(seed121);
    for (const want of VEC.layers.doubles) expect(rng.nextDouble()).toBe(want);
  });

  it("ziggurat normals match", () => {
    const rng = new Pcg64(seed121);
    for (const want of VEC.layers.normals) expect(rng.nextNormal()).toBe(want);
  });

  it("ziggurat exponentials match", () => {
    const rng = new Pcg64(seed121);
    for (const want of VEC.layers.exponentials) expect(rng.nextExponential()).toBe(want);
  });

  for (const [key, shape] of [["gamma_67_7", 67.7], ["gamma_3_3", 3.3], ["gamma_0_5", 0.5]] as const) {
    it(`standard gamma(${shape}) matches`, () => {
      const rng = new Pcg64(seed121);
      for (const want of VEC.layers[key]) expect(sampleGamma(rng, shape)).toBe(want);
    });
  }

  for (const [key, c] of Object.entries(VEC.cases) as [string, any][]) {
    it(`§${key} interleaved beta stream matches`, () => {
      const rng = new Pcg64(BigInt(c.seed));
      const quads = ["identity", "custody", "material", "risk"];
      let i = 0;
      for (let round = 0; round < 32; round++) {
        for (const q of quads) {
          const [a, b] = c.posteriors[q];
          expect(sampleBeta(rng, a, b)).toBe(c.beta_stream[i++]);
        }
      }
    });
  }
});
